---
name: Bug Report
description: Bug Report
title: "bug: "
labels: ["bug"]
assignees:
  - attilasomogyi

body:
  - type: dropdown
    id: component
    attributes:
      label: Effected component
      description: Effected component
      multiple: true
      options:
      
      
        - ".editorconfig
.gitignore
.prettierrc.json
.releaserc.json
CHANGELOG.md
CODE_OF_CONDUCT.md
CODE_OF_CONDUCT.md.j2
CONTRIBUTING.md
CONTRIBUTING.md.j2
LICENSE
Makefile
PULL_REQUEST_TEMPLATE.md
README.md
README.md.j2
auto-release.yml
bug_report.yml
bug_report.yml.j2
build-documentation.yml
conf.py
conf.py.j2
config.yml
custom.css
custom.js
dark.css
default_dark.js
default_light.js
delete-old-workflow-runs.yml
deploy-github-pages.yml
extensions.json
feature_request.yml
general.css
index.rst
index.rst.j2
initialize-code-of-conduct.yml
initialize-conf-py.yml
initialize-contributing.yml
initialize-index-rst.yml
initialize-readme.yml
make.bat
repository-template.yml
requirements.txt
settings.json
theme_switcher.js
update-bug-report-template.yml"
      
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: Effected version
      description: Effected version
      multiple: false
      options:
      
      
        - ""
      
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: environment
      multiple: true
      options:
        - "GNU/Linux Distribution"
        - "BSD Distribution"
        - "MacOSX"
        - "Windows"
    validations:
      required: true

  - type: dropdown
    id: severity-level
    attributes:
      label: Severity level
      description: Severity level
      multiple: false
      options:
        - "s1: critical"
        - "s2: major"
        - "s3: minor/moderate"
        - "s4: low"
    validations:
      required: true

  - type: dropdown
    id: priority-level
    attributes:
      label: Priority level
      description: Priority level
      multiple: false
      options:
        - "p1: immediate/critical"
        - "p2: high"
        - "p3: medium"
        - "p4: low"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: "Bug description"
      value: "Bug description"
      render: bash
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction steps
      description: "How do you trigger this bug? Please walk us through it step by step."
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true

  - type: textarea
    id: expected-result
    attributes:
      label: Expected result
      description: "Expected result"
      value: "Expected result..."
      render: HTML
    validations:
      required: true

  - type: textarea
    id: actual-result
    attributes:
      label: Actual result
      description: "Actual result"
      value: "Actual result..."
      render: HTML
    validations:
      required: true
