blank_issues_enabled: false
contact_links:
  - name: Github Actions Workflows questions on StackOverflow
    url: https://stackoverflow.com/questions/tagged/github-actions-workflows
    about: Please ask and answer questions here.
