name: Auto Release

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node Package Lock File
        run: |
          npm init -y
          npm i --package-lock-only
        shell: dash -e {0}

      - name: Node Cache
        uses: actions/setup-node@v3
        with:
          node-version: current
          cache: "npm"

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
