name: Auto Release

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
      
      - name: Update Bug Report Template
        uses: attilasomogyi/github-actions-workflows/.github/workflows/update-bug-report-template.yml@main
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


