name: Auto Release

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

  workflow_call:

jobs:
  auto-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-bug-report-template:
    needs: auto-release
    uses: attilasomogyi/github-actions-workflows/.github/workflows/update-bug-report-template.yml@main

  update-security-template:
    needs: auto-release
    uses: attilasomogyi/github-action-workflows/.github/workflows/update-security.yml@main
