name: Initialize conf.py

on:
  workflow_dispatch:

jobs:
  initialize-conf-py:
    uses: attilasomogyi/github-actions-workflows/.github/workflows/repository-template.yml@main
    with:
      jinja2-input-data: "-D repository_name=$REPOSITORY_NAME -D repository_owner=$GITHUB_REPOSITORY_OWNER"
      jinja2-input-template-file: ".github/workflows/repository-templates/conf.py.j2"
      jinja2-output-file: "docs/source/conf.py"
      commit-message: "docs(source): update conf.py"
