name: Initialize LICENSE

on:
  workflow_dispatch:

jobs:
  initialize-license:
    uses: attilasomogyi/github-actions-workflows/.github/workflows/repository-template.yml@main
    with:
      jinja2-input-data: "-D year=$(date +'%Y') -D copyright_holders=$(git log --max-count='20' --format='%aN' | sort | uniq | grep '^[[:upper:]]')"
      jinja2-input-template-file: ".github/workflows/repository-templates/LICENSE.j2"
      jinja2-output-file: "LICENSE"
      commit-message: "docs(license): update license"
