name: Repository Template

on:
  workflow_dispatch:

  workflow_call:
    inputs:
      jinja2-input-data:
        required: true
        type: string
      jinja2-input-template-file:
        required: true
        type: string
      jinja2-output-file:
        required: true
        type: string
      commit-message:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pyhton Cache
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Repository Template
        run: |
          pip install --upgrade pip
          pip install jinja2-cli
          REPOSITORY_NAME=$(basename $GITHUB_REPOSITORY)
          COMPONENTS=$(find . -type f  -not -path '*\.git\/*' -exec basename {} \; | sort --uniqu)
          COMPONENTS=$(echo $COMPONENTS | sed -e 's/\s\+/,/g')
          set -x
          git tag
          LATEST_VERSION=$(git tag | sort --version-sort | tail -1)
          jinja2 --strict ${{ inputs.jinja2-input-data }} ${{ inputs.jinja2-input-template-file }} > ${{ inputs.jinja2-output-file }}
        shell: dash -e {0}

      - name: Pull Current Changes
        run: |
          git pull --rebase --autostash
        shell: dash -e {0}

      - name: Committing Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ inputs.commit-message }}
