name: Update SECURITY.md

on:
  workflow_dispatch:

jobs:
  update-security:
    uses: attilasomogyi/github-actions-workflows/.github/workflows/repository-template.yml@main
    with:
      jinja2-input-data: "-D latest_version=$LATEST_VERSION"
      jinja2-input-template-file: ".github/workflows/repository-templates/SECURITY.md.j2"
      jinja2-output-file: "SECURITY.md"
      commit-message: "docs(security): update security.md"
